---
- hosts: all
  become: yes
  tasks:
  - name: copy the manifest to master
    copy:
      src: /var/lib/jenkins/workspace/release-pipeline/kubectl-deploy.yaml
      dest: /home/ubuntu
            
  - name: deploy the application and expose as NodePort
    shell: kubectl apply --kubeconfig=/home/ubuntu/.kube/config -f /home/ubuntu/kubectl-deploy.yaml  && kubectl get deploy --kubeconfig=/home/ubuntu/.kube/config && kubectl get svc --kubeconfig=/home/ubuntu/.kube/config

