apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-jenkins
  labels:
    app: docker-jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-jenkins
  template:
    metadata:
      labels:
        app: docker-jenkins
    spec:
      containers:
      - name: docker-jenkins-ctr
        image: account_id/docker-jenkins:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: docker-jenkins-svc
spec:
  selector:
    app: docker-jenkins
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
  type: NodePort
